{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.secret.name }}
stringData:
  accessKeyID: {{ .Values.secret.accessKey }}
  secretAccessKey: {{ .Values.secret.secretKey }}
  endpoint: {{ .Values.secret.endpoint }}
{{- end -}}
{{- if .Values.secret.usePrefix }}
  usePrefix: "true"
{{- end }}
  prefix: "{{ .Values.secret.prefix }}"
